[package]
name = "boimp"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { git = "https://github.com/robtfm/bevy", branch = "release-0.16-dcl", default-features=false, features = [
    "bevy_core_pipeline",
    "bevy_render", 
    "bevy_pbr",
    "bevy_log",
    "bevy_asset"
] }
wgpu = "24"
crossbeam-channel = "*"
async-channel = "*"
image = { version = "*", default-features = false, features = ["png"] }
bytemuck = "*"

# asset loader
zip = { version = "2", default-features = false }
anyhow = "*"
serde = { version = "1", features = ["derive"] }

# examples
[dev-dependencies]
pico-args = "0.5.0"
rand = "0.8.5"
bevy = { git = "https://github.com/robtfm/bevy", branch = "release-0.16-dcl", default-features = true }
